name: Deploy to Orange Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        shell: pwsh
        run: |
          $privateKeyPath = "C:\Users\aidan\.ssh\id_rsa"
          $hosts = @("100.97.252.126", "100.77.148.8")

          foreach ($host in $hosts) {
            Write-Host "Deploying to $host..."

            $sshCommand = @"
            ssh -i $privateKeyPath -o StrictHostKeyChecking=no admin@$host '
              cd ~/modbus &&
              git pull | tee /tmp/gitlog &&
              if ! grep -q "Already up to date" /tmp/gitlog; then
                echo "[CI/CD] Restarting my-app.service at \$(date)" >> ~/modbus/deploy.log &&
                sudo systemctl restart my-app.service
              else
                echo "[CI/CD] No changes. Skipping restart at \$(date)" >> ~/modbus/deploy.log
              fi
            '
            "@ -replace "`r", ""

            Invoke-Expression $sshCommand
          }
