name: Deploy to Orange Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Orange Pi
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 100.97.252.126
          username: admin
          key_path: C:\Users\aidan\.ssh\id_rsa
          script: |
            echo "✅ Connected to Orange Pi"
            cd ~/modbus
            git pull
            systemctl restart my-app
