name: Deploy to Orange Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        shell: pwsh
        run: |
          $privateKey = Get-Content "C:\Users\aidan\.ssh\id_rsa"
          $hosts = @("100.97.252.126", "100.77.148.8")  # додай IP другого Orange Pi

          foreach ($host in $hosts) {
            Write-Host "Deploying to $host..."
            $sshCommand = "ssh -i C:\Users\aidan\.ssh\id_rsa -o StrictHostKeyChecking=no admin@$host 'cd ~/modbus && git pull && echo \"admin\" | sudo -S systemctl restart my-app'"
            Invoke-Expression $sshCommand
          }

