name: Deploy to Orange Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        shell: pwsh
        run: |
          $privateKey = Get-Content "C:\Users\aidan\.ssh\id_rsa"
          $sshCommand = @"
          ssh -i C:\Users\aidan\.ssh\id_rsa -o StrictHostKeyChecking=no admin@100.97.252.126 '
            cd ~/modbus &&
            git pull &&
            sudo systemctl restart my-app
          '
          "@
          Invoke-Expression $sshCommand
